export { default as Login } from '../pages/Login';
export { default as Register } from '../pages/Register';
export { default as Profile } from '../pages/Profile';
export { default as Home } from '../pages/Home';
export { default as Header } from './Header';
export { Stars } from './Background';
export { default as CreatePost } from '../pages/CreatePost';
export { default as EditProfile } from '../pages/EditProfile';
export { default as Friends } from '../pages/Friends';
export { default as LoadingScreen } from '../pages/LoadingScreen';
