export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Profile } from './Profile';
export { default as Home } from './Home';
export { default as Header } from './Header';
export { default as Stars } from './Background';
export { default as CreatePost } from './CreatePost';
export { default as CreditForm } from './CreditForm';
export { default as CardExp } from './CardExp';
export { default as Dice} from './Background2';
